version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ashketchum
      POSTGRES_PASSWORD: pikachu
      POSTGRES_DB: pokemons
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=ashketchum@pokemon.com
      - PGADMIN_DEFAULT_PASSWORD=pikachu
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80



  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080